### ISSUE TITLE
Project no longer builds

### ISSUE THREAD

**Issue by pf-costa** [anater/useReduction#4]
After merging the PR https://github.com/anater/useReduction/pull/2/files, it is no longer possible to build the project. There are two tests files, which are similar, in two folders: lib and test. The one from the lib folder is outdated. @anater shouldn't there be only one test file?

**Comment by anater** [comment]
That's correct. I assumed the old test file had been replaced in that PR. I'll need to remove it and merge that change. Are you building off development or master branch?

**Comment by pf-costa** [comment]
From development. Thanks for the quick reply!
